name: wave_res

channels:
  - anaconda

dependencies:
  - python=2.7
  - matplotlib
  - numpy
  - netcdf4
  - ipython=4.2
  - tqdm
  - pathlib2
  - scipy=1.1
  - h5py
  - pip:
     - "git+https://github.com/lkilcher/pyDictH5.git@v0.2.1#egg=pyDictH5"
